pipeline {
    agent any

    tools {
        jdk 'jdk17'  // your JDK
    }

    environment {
        KARATE_DIR = 'karate'
        REPORTS_DIR = 'reports'
    }

    stages {

        stage('Pipeline Check') {
            steps {
                echo "✅ Jenkins pipeline is running!"
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Run Karate Tests') {
            steps {
                dir("${KARATE_DIR}") {
                    echo "🏃 Running Karate tests using Maven wrapper..."
                    // Make mvnw executable
                    sh 'chmod +x mvnw'
                    // Run all tests in Karate folder
                    sh './mvnw clean test'
                }
            }
        }

        stage('Archive Test Results') {
            steps {
                dir("${KARATE_DIR}") {
                    // Archive JUnit XML reports generated by Karate
                    junit '**/target/surefire-reports/*.xml'
                    // Archive HTML reports if you generate them
                    archiveArtifacts artifacts: '**/target/karate-reports/*.html', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        success {
            echo "🎉 Pipeline completed successfully!"
        }
        failure {
            echo "❌ Build or tests failed. Check console output for details."
        }
        always {
            echo "📝 Pipeline finished. Review the stages and test results above."
        }
    }
}